-- 검색 trgm 인덱스 배선 — 인덱스가 없던 게 아니라 **쿼리가 그 식으로 묻지 않았다**.
--
-- ── 어떻게 드러났나 ────────────────────────────────────────────────────────
--
-- Supabase 성능 어드바이저가 `posts_trgm_idx` 와 `facilities_norm_name_trgm_gix` 를
-- "미사용 인덱스 — 삭제 후보" 로 신고했다. 그 조언을 그대로 따랐다면 유일한 단서가
-- 사라졌을 것이다. 왜 안 쓰이는지를 보니 원인이 서로 달랐다.
--
-- ① posts — 인덱스는 **연결식**에 걸려 있는데 앱은 **두 컬럼을 따로** 묻는다.
--
--      인덱스: gin ((coalesce(title,'') || ' ' || coalesce(content,'')) gin_trgm_ops)
--      앱    : q.or('title.ilike.%term%,content.ilike.%term%')   ← community_repository
--
--    trgm GIN 은 인덱스에 적힌 **그 식 그대로** 물었을 때만 쓰인다. 컬럼을 따로
--    쓰면 인덱스에 그 컬럼의 트라이그램이 없으므로 후보조차 되지 못한다.
--    `enable_seqscan=off` 로 강제해도 Seq Scan 이 나온다(= 선택의 문제가 아니라
--    사용 불가). 뷰 때문이 아니다 — v_post_feed 에 security_barrier 가 없어
--    술어는 정상적으로 밀려 내려간다.
--
-- ② facilities — 인덱스는 **정규화된 이름**, 검색은 **원본 이름**.
--
--      인덱스: gin (app.norm_biz_text(name) gin_trgm_ops)
--      검색  : facilities_search 의 `f0.name ilike '%' || p_query || '%'`
--
--    이쪽은 **결함이 아니다.** 그 인덱스는 검색용이 아니라 업체 자동매칭용이다
--    (0025 — norm_biz_text 를 참조하는 함수는 apply_business_profile 하나뿐).
--    업체 신청이 아직 드물어 "미사용" 으로 보일 뿐이다. 그래서 **지우지 않는다.**
--    문제는 그 옆에서 facilities_search 가 인덱스 없이 24,552 행을 훑고 있었다는 것.
--
-- ── 왜 지금 고치나 ────────────────────────────────────────────────────────
--
-- 이건 "규모가 오면 느려진다" 가 아니라 **이미 느리다**. 지도 검색창이 입력마다
-- 337ms 를 쓴다(아래 실측). posts 는 31 행이라 아직 티가 안 나지만 같은 구멍이다.
--
-- 그리고 이 유형이 특히 나쁘다 — **인덱스가 있으니 "검색은 인덱싱돼 있다" 고 믿게
-- 된다.** 없으면 리뷰에서 눈에 띈다. 어드바이저마저 정반대 신호("삭제 후보")를
-- 보여주므로 스스로 드러날 경로가 없다.
--
-- ── 실측 (2026-08-05, 운영 DB, 롤백 검증) ─────────────────────────────────
--
-- facilities_search 의 실제 쿼리 형태(거리순 정렬 포함), p_query='동물병원'
-- — 24,552 행 중 5,972 행 일치라 사실상 최악에 가까운 항이다:
--
--   현재 (인덱스 없음)   Seq Scan 24,552 행, 18,580 행 버림      337 ms
--   아래 인덱스 적용 후  Bitmap Index Scan (인덱스 1.07ms)       143 ms
--
-- posts 는 `enable_seqscan=off` 로 사용 가능 여부만 확인했다(31 행이라 시간은 무의미):
--
--   현재            Seq Scan (강제해도 인덱스 사용 불가)
--   적용 후         BitmapOr → title 인덱스 + content 인덱스 둘 다 사용
--
-- ── 왜 이 모양인가 ────────────────────────────────────────────────────────
--
-- 앱 쿼리를 인덱스 식에 맞추는 방법도 있었다(생성 컬럼 + 뷰 노출, 또는 검색 RPC).
-- 그러나 그건 **앱·뷰·인덱스 셋을 동시에 바꾸는** 일이고, 그 과정에서 검색 결과가
-- 미묘하게 달라진다(정규화가 무엇을 지우느냐에 따라). 여기서는 **동작을 한 글자도
-- 바꾸지 않고** 인덱스만 쿼리에 맞춘다. 지금 필요한 건 의미 변경이 아니라 배선이다.
--
-- 컬럼 타입 때문에 캐스트가 다르다 — title·name 은 varchar(gin_trgm_ops 는 text
-- 연산자 클래스라 ::text 필요), content 는 이미 text.

-- ① 게시글 검색 — 앱이 두 컬럼을 따로 묻는 그 형태에 맞춘다. 플래너가 BitmapOr 로
--    둘을 합친다(둘 중 하나만 만들면 나머지 한쪽 때문에 결국 전량 스캔이다).
create index posts_title_trgm_idx   on public.posts using gin ((title::text) gin_trgm_ops);
create index posts_content_trgm_idx on public.posts using gin (content gin_trgm_ops);

-- ② 위 둘로 대체되는 옛 연결식 인덱스를 지운다.
--
--    남겨 둘 이유가 없다 — **어떤 쿼리도 이 식으로 묻지 않고**(전수 확인), 그 사실을
--    위에서 강제 플랜으로 증명했다. 크기(31 행)는 문제가 아니지만, 남겨 두면 다음
--    사람이 이번과 똑같이 "게시글 검색은 trgm 인덱스가 있다" 고 읽는다. 그 오해가
--    이 마이그레이션이 늦어진 이유다.
--
--    나중에 연결식으로 묻는 검색 RPC 를 만들 일이 생기면 그때 다시 만들면 된다.
drop index if exists public.posts_trgm_idx;

-- ③ 시설 검색 — facilities_search 가 실제로 쓰는 원본 name 형태.
--    app.norm_biz_text(name) 인덱스는 **그대로 둔다**(업체 자동매칭용, 위 주석 ②).
create index facilities_name_trgm_idx on public.facilities using gin ((name::text) gin_trgm_ops);
